### ISSUE TITLE
failed to open stream : badawy/embedly/src/config/embedly.php

### ISSUE THREAD

**Issue by kupendra** [elbadawy/embedly-laravel#1]
I think here is the problem with file name in case sensitive `config/Embedly.php`

In `README.md`  Installation step 5 say add your api key in `config/embedly.php` file but ther is camel case in file name `config/Embedly.php` so it works fine in local but when deploy in live then following error generated.

`PHP Warning:  Uncaught exception 'ErrorException' with message 'require(/tmp/build_39cc326bfb7cbdb597747756cbad38a9/fodacode-laravel-bfafe54d085eab36fab094612ac605efc04c6eea/laravel/vendor/badawy/embedly/src/config/embedly.php): failed to open stream: No such file or directory' in /tmp/build_39cc326bfb7cbdb597747756cbad38a9/fodacode-laravel-bfafe54d085eab36fab094612ac605efc04c6eea/laravel/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:66`

**Comment by badawys** [comment]
Fixed in version 1.0.1 

Thank You kupendra :+1:
