### ISSUE TITLE
Worked about a year ago

### ISSUE THREAD

**Issue by jakeYeager** [elbadawy/embedly-laravel#10]
Error:
```bash
[Symfony\Component\Debug\Exception\FatalErrorException]              
  Call to undefined method Illuminate\Foundation\Application::share()  
```
...when I try `vendor:publish` (after adding service providers/facades to config/app.php).

Vanilla Laravel 5.4 install...

Tried a couple of package version:
```bash
"php": ">=5.6.4",
"laravel/framework": "5.4.*",
"laravel/tinker": "~1.0",
"badawy/embedly": "1.0.4"
```
...and

```bash
"badawy/embedly": "^1.0",
```
... and 
```bash
"badawy/embedly": "1.*",
```
Same error.

Don't know if this is a bug or if it has to do with Embedly API adjustments. Maybe something that I have overlooked in my install?

Thanks!

**Comment by badawys** [comment]
Embeldy did a stupid move, that now require ONLY paid plans to work, so if you are using this package with API key associated with an old free account, it will not work

**Comment by jakeYeager** [comment]
Understood. Thanks for the update
