### ISSUE TITLE
laravel 5.2

### ISSUE THREAD

**Issue by mbcbus** [elbadawy/embedly-laravel#5]
Hello, trying to add this to Laravel 5.2. Any chance you'll be updating soon?

"Your requirements could not be resolved to an installable set of packages."

**Comment by badawys** [comment]
Just updated to work with laravel 5.2 and 5.3

**Comment by vmitchell85** [comment]
@elbadawy Can you tag a release so I dont' have to use dev?

**Comment by badawys** [comment]
@vmitchell85 you can now use v1.0.2
